### PR TITLE
Updating Nuget Packages and Project files.

### PR DESCRIPTION
**Pull request by houseofcat**
Adds support to both the latest versions of Unity (Unity.Abstractions) and Xunit and the pain in the butt Xunit.Analyzer update/change.

Also one minor change, set C# language version to Latest Minor.

### CODE REVIEW

**Comment by houseofcat** [comment]
- Added Unity latest version support.
- Implemented some minor stylistic changes from Rosylnator and myself and missing comments.

**Comment by houseofcat** [comment]
@HongGit @StephenMolloy

**Comment by cdonnellytx** [comment]
Hi all, my company just hit this issue and was wondering if this library will be updated with a new release?  We're unfortunately stuck with WebForms for a bit longer and need an update...

**Comment by HongGit** [comment]
Please note that the Readme has been updated:
"**Please note that this implementation is for demonstration purposes only and is not being actively maintained.**"

**Comment by houseofcat** [comment]
One could argue this demonstration is out of date then if it no longer applies to Unity dependency injection as it is currently released. Also if it was truly intended to be just a Demo, you should not have released Nuget packages (preventing dependency on your released package.)

Disappointing really as I have done all the work for you. Regardless, I will create my own solution and release the Nugets later today or tomorrow.

@cdonnellytx @HongGit

**Comment by houseofcat** [comment]
https://github.com/houseofcat/DependencyInjection.WebForms.Unity

@cdonnellytx

**Pull request closed without merging**
